### PR TITLE
Added Zoom to Office 1.35

### PR DESCRIPTION
**Pull request by patryk-kubiczek**
I added an action to Office 1.35: by pressing space a pre-defined link to a Zoom meeting is triggered. 

It works as expected hence I recommend this pull request.

### CODE REVIEW

**Comment by tovogt** [comment]
Interesting, thanks for testing! Would it make sense to somehow mark this visually on the map or is it better to keep it as a "hidden" feature because the room is supposed to be a "private" meeting room? Currently, the zoom room is linked to a specific account and (therefore) to a specific host, right? And so zoom will only let you in, as long as the host is there, too, right?

**Comment by patryk-kubiczek** [comment]
It was meant to be a semi-private meeting room since the link uses my zoom account. However, I believe the meeting can be joined anytime, even without the host (it is password-protected though).

Ideally we will have more people / groups creating their zoom links, preferably at their offices, so we can have "business meetings" also taking place in PIK Adventure. We could add a small marking to rooms which have zoom associated with them.

**Comment by tovogt** [comment]
So, if you need to provide participants with a password anyway, you can directly send them both the link and the password, right? What's the point of having that area if it won't work without a private text chat exchange anyways?

**Comment by patryk-kubiczek** [comment]
I think the necessity to share the password is not an issue:

1. The password will be fixed and easy to remember so the "private exchange" will hopefully have to happen only once. And then users can actually avoid a repeated exchange of the zoom link as they would simply agree to "meet at Office 1.35".
2. The most important feature of the PIK Adventure is the spatial context for meetings it provides; other users can see the location of your avatar so even if your meeting is over the zoom, they will see you taking part in it. Obviously, with this zoom setup as I'm proposing you can connect without having to enter PIK Adventure; also within PIK Adventure your avatar can leave the "meeting office" and still stay in the zoom meeting. But I think this extra flexibility is even desirable as people who for some reasons might not want to use PIK Adventure can still be part of meetings.

**Comment by tovogt** [comment]
Thanks for the clarification!

Okay, would you like to add a marking tile for rooms with zoom associated with them? Or should I merge first and we will come back to this later?

**Comment by patryk-kubiczek** [comment]
I added a zoom icon to Office 1.35. It was not clear to me how to add new tiles to existing tilesets so I just created a new external tileset in file extra_tiles.tsx. It seems to be easy now to add even more tiles just by copying a .png file and modifying extra_tiles.tsx accordingly.

Please let me know if you would do it differently.

**Comment by tovogt** [comment]
For workadventure, all tile sets need to be embedded: "You cannot refer to an external tileset in a TSX file. Click the "embed tileset" button in the tileset tab to embed tileset data." (https://workadventu.re/map-building/wa-maps) You add new tiles by either modifying existing tileset PNGs in place using a tool like GIMP. Or you add a new image using the "New tileset" button in in the tileset tab. Again, make sure to embed the tileset data when doing this.

**Comment by patryk-kubiczek** [comment]
Thanks for pointing that out, I missed that part of the documentation. Now the zoom icon is in a new embedded tileset "zoom". It is probably not an optimal solution to add a new tileset for each new icon but for the moment it works.

**Comment by tovogt** [comment]
Thanks for making the effort to get familiar with Tiled and all those technicalities!

I added your new tile to one of the existing tile sets and took the opportunity to rename all the existing tile sets.

The changes are now live! :)

**Pull request merged**
